// models/Payment.js
import mongoose, { model } from 'mongoose';
const { Schema } = mongoose;


const paymentSchema = new Schema({
    razorpay_order_id: {
        type: String,
        required: true
    },
    razorpay_payment_id: {
        type: String,
        required: true
    },
    razorpay_signature: {
        type: String,
        required: true
    },
    amount: {
        type: Number,
        required: true  // Store the total amount paid by the customer
    },
    userId: {
        type: String,
        required: true  // Store customer name
    },
    receipt: {
        type: String,
        required: true  // Store the receipt generated by Razorpay
    },
    date: {
        type: Date,
        required: true,  // Store the date of payment
        default: Date.now
    },
    
}, { timestamps: true });

// const Payment = mongoose.model('Payment', paymentSchema);


export default model('payment',paymentSchema);
